-- -- 
-- 
-- 
-- CREATE TABLE tx_ptextlist_domain_model_list (
-- 	uid int(11) unsigned DEFAULT '0' NOT NULL auto_increment,
-- 	pid int(11) DEFAULT '0' NOT NULL,
-- 	tstamp int(11) unsigned DEFAULT '0' NOT NULL,
-- 	crdate int(11) unsigned DEFAULT '0' NOT NULL,
-- 	deleted tinyint(4) unsigned DEFAULT '0' NOT NULL,
-- 	hidden tinyint(4) unsigned DEFAULT '0' NOT NULL,
-- 
-- 	t3ver_oid int(11) DEFAULT '0' NOT NULL,
-- 	t3ver_id int(11) DEFAULT '0' NOT NULL,
-- 	t3ver_wsid int(11) DEFAULT '0' NOT NULL,
-- 	t3ver_label varchar(30) DEFAULT '' NOT NULL,
-- 	t3ver_state tinyint(4) DEFAULT '0' NOT NULL,
-- 	t3ver_stage tinyint(4) DEFAULT '0' NOT NULL,
-- 	t3ver_count int(11) DEFAULT '0' NOT NULL,
-- 	t3ver_tstamp int(11) DEFAULT '0' NOT NULL,
-- 	t3_origuid int(11) DEFAULT '0' NOT NULL,
-- 
-- 	sys_language_uid int(11) DEFAULT '0' NOT NULL,
-- 	l18n_parent int(11) DEFAULT '0' NOT NULL,
-- 	l18n_diffsource mediumblob NOT NULL,
-- 
-- 	
-- 	listItems int(11) unsigned DEFAULT '0'
-- 	
-- 
-- 	
-- 
-- 	PRIMARY KEY (uid),
-- 	KEY parent (pid),
-- );
-- 
-- CREATE TABLE tx_ptextlist_domain_model_listitem (
-- 	uid int(11) unsigned DEFAULT '0' NOT NULL auto_increment,
-- 	pid int(11) DEFAULT '0' NOT NULL,
-- 	tstamp int(11) unsigned DEFAULT '0' NOT NULL,
-- 	crdate int(11) unsigned DEFAULT '0' NOT NULL,
-- 	deleted tinyint(4) unsigned DEFAULT '0' NOT NULL,
-- 	hidden tinyint(4) unsigned DEFAULT '0' NOT NULL,
-- 
-- 	t3ver_oid int(11) DEFAULT '0' NOT NULL,
-- 	t3ver_id int(11) DEFAULT '0' NOT NULL,
-- 	t3ver_wsid int(11) DEFAULT '0' NOT NULL,
-- 	t3ver_label varchar(30) DEFAULT '' NOT NULL,
-- 	t3ver_state tinyint(4) DEFAULT '0' NOT NULL,
-- 	t3ver_stage tinyint(4) DEFAULT '0' NOT NULL,
-- 	t3ver_count int(11) DEFAULT '0' NOT NULL,
-- 	t3ver_tstamp int(11) DEFAULT '0' NOT NULL,
-- 	t3_origuid int(11) DEFAULT '0' NOT NULL,
-- 
-- 	sys_language_uid int(11) DEFAULT '0' NOT NULL,
-- 	l18n_parent int(11) DEFAULT '0' NOT NULL,
-- 	l18n_diffsource mediumblob NOT NULL,
-- 
-- 	
-- 	 int(11) unsigned DEFAULT '0'
-- 	
-- 
-- 	
-- 	list_uid int(11) unsigned DEFAULT '0'
-- 	
-- 	listitem_uid int(11) unsigned DEFAULT '0'
-- 	
-- 
-- 	PRIMARY KEY (uid),
-- 	KEY parent (pid),
-- );
-- 
-- CREATE TABLE tx_ptextlist_domain_model_simplelistitem (
-- 	uid int(11) unsigned DEFAULT '0' NOT NULL auto_increment,
-- 	pid int(11) DEFAULT '0' NOT NULL,
-- 	tstamp int(11) unsigned DEFAULT '0' NOT NULL,
-- 	crdate int(11) unsigned DEFAULT '0' NOT NULL,
-- 	deleted tinyint(4) unsigned DEFAULT '0' NOT NULL,
-- 	hidden tinyint(4) unsigned DEFAULT '0' NOT NULL,
-- 
-- 	t3ver_oid int(11) DEFAULT '0' NOT NULL,
-- 	t3ver_id int(11) DEFAULT '0' NOT NULL,
-- 	t3ver_wsid int(11) DEFAULT '0' NOT NULL,
-- 	t3ver_label varchar(30) DEFAULT '' NOT NULL,
-- 	t3ver_state tinyint(4) DEFAULT '0' NOT NULL,
-- 	t3ver_stage tinyint(4) DEFAULT '0' NOT NULL,
-- 	t3ver_count int(11) DEFAULT '0' NOT NULL,
-- 	t3ver_tstamp int(11) DEFAULT '0' NOT NULL,
-- 	t3_origuid int(11) DEFAULT '0' NOT NULL,
-- 
-- 	sys_language_uid int(11) DEFAULT '0' NOT NULL,
-- 	l18n_parent int(11) DEFAULT '0' NOT NULL,
-- 	l18n_diffsource mediumblob NOT NULL,
-- 
-- 	
-- 
-- 	
-- 
-- 	PRIMARY KEY (uid),
-- 	KEY parent (pid),
-- );
-- 
-- CREATE TABLE tx_ptextlist_domain_model_complexlistitem (
-- 	uid int(11) unsigned DEFAULT '0' NOT NULL auto_increment,
-- 	pid int(11) DEFAULT '0' NOT NULL,
-- 	tstamp int(11) unsigned DEFAULT '0' NOT NULL,
-- 	crdate int(11) unsigned DEFAULT '0' NOT NULL,
-- 	deleted tinyint(4) unsigned DEFAULT '0' NOT NULL,
-- 	hidden tinyint(4) unsigned DEFAULT '0' NOT NULL,
-- 
-- 	t3ver_oid int(11) DEFAULT '0' NOT NULL,
-- 	t3ver_id int(11) DEFAULT '0' NOT NULL,
-- 	t3ver_wsid int(11) DEFAULT '0' NOT NULL,
-- 	t3ver_label varchar(30) DEFAULT '' NOT NULL,
-- 	t3ver_state tinyint(4) DEFAULT '0' NOT NULL,
-- 	t3ver_stage tinyint(4) DEFAULT '0' NOT NULL,
-- 	t3ver_count int(11) DEFAULT '0' NOT NULL,
-- 	t3ver_tstamp int(11) DEFAULT '0' NOT NULL,
-- 	t3_origuid int(11) DEFAULT '0' NOT NULL,
-- 
-- 	sys_language_uid int(11) DEFAULT '0' NOT NULL,
-- 	l18n_parent int(11) DEFAULT '0' NOT NULL,
-- 	l18n_diffsource mediumblob NOT NULL,
-- 
-- 	
-- 
-- 	
-- 
-- 	PRIMARY KEY (uid),
-- 	KEY parent (pid),
-- );
-- 
-- 
-- 	
-- 		
-- 	
-- 
-- 	
-- 		
-- 	
-- 
-- 	
-- 
-- 	
