services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false


  PunktDe\PtExtlist\Controller\:
    resource: '../Classes/Controller/*'

  PunktDe\PtExtlist\ExtlistContext\:
    resource: '../Classes/ExtlistContext/*'

  PunktDe\PtExtlist\Domain\Model\Lists\:
    resource: '../Classes/Domain/Model/Lists/*'
    public: true
